### ISSUE TITLE
The dcimg file obtained with the usb3.0 communication protocol can not be read normally using the dcimg library.

### ISSUE THREAD

**Issue by dzh929** [lens-biophotonics/dcimg#11]
The dcimg file obtained with the cameralink communication protocol is normal, but the dcimg file obtained with the usb3.0 communication protocol can not be read normally using the dcimg library.
The image that appears  in HCimageLife software is fine,
![image](https://user-images.githubusercontent.com/61380549/125463271-9115a01c-455f-4e0e-8919-13bec752d490.png)
However，there is an error in the file when I read with the dcimg library
![image](https://user-images.githubusercontent.com/61380549/125463225-1b3682a0-6afa-4375-adb6-9aa35eaf992c.png)
Python prompts a warning
`
lib\site-packages\dcimg.py:365: RuntimeWarning: divide by zero encountered in floor_divide
  self._target_line = (1023 - self.y0) // self.binning
`

**Comment by gmazzamuto** [comment]
That's strange... can you please attach the original dcimg file? I'll try to look into it when I have some time

**Comment by dzh929** [comment]
Thank you for your help, and we have found the reason. Dcimg file acquired in USB communication protocol actually has no the step '4px_correction', so the calculation of 'strides' in dcimg.py should be '+16' instead of '+32'. We have correct it in the dcimg.py, we also give you two example file to compare and verify it. Maybe other bugs still exist, we hope you can correct the library in the next version.
[DCIMGTEST.zip](https://github.com/lens-biophotonics/dcimg/files/6813211/DCIMGTEST.zip)

**Comment by gmazzamuto** [comment]
Hi, looking at the image that you provided I made an attempt to support both usb and cameralink file formats. Unfortunately this is all reverse engineering, so this might brake something else. If you can, it would be great if you could test this new version of `dcimg.py` also with some exotic configurations (e.g. cropping, binning, etc) and both with cameralink and usb. Otherwise, just let me know if this new version works for your use case, then I will publish it.
